---

name: Publish Response Area

outputs:
  pages-url:
    description: GitHub Pages deployment URL
    value: ${{ steps.deploy-pages.outputs.page_url }}

runs:
  using: composite
  steps:
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '20.14.0'
        registry-url: 'https://npm.pkg.github.com'
    - name: Install dependencies
      run: yarn install
      shell: bash
    - name: Build Web Components
      run: yarn build
      shell: bash
    - name: Build Storybook
      run: yarn build-storybook
      shell: bash
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: storybook-static/
    - name: Deploy Pages artifact
      id: deploy-pages
      uses: actions/deploy-pages@v4
